# Generated by Django 3.2.3 on 2021-08-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeditor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicform',
            name='title',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='basicform',
            name='username',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
