# Generated by Django 3.2.3 on 2021-08-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeditor', '0002_auto_20210802_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicform',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='basicform',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=25),
        ),
    ]
