# Generated by Django 3.2.3 on 2021-08-07 14:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myeditor', '0003_auto_20210802_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicform',
            name='realtext',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
